// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs3Tf-S21vXyxK4z3l4WZ7zj_yLmESDa4',
    appId: '1:1037548014539:web:e9dc712ca1f2cca5eac44e',
    messagingSenderId: '1037548014539',
    projectId: 'estoquepro-dev',
    authDomain: 'estoquepro-dev.firebaseapp.com',
    databaseURL: 'https://estoquepro-dev-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-dev.firebasestorage.app',
    measurementId: 'G-LD4QHBSJ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_18-GqeGl2NV-w_Inwv4vA5G9UItIC10',
    appId: '1:1037548014539:android:c54c37515ab1837eeac44e',
    messagingSenderId: '1037548014539',
    projectId: 'estoquepro-dev',
    databaseURL: 'https://estoquepro-dev-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76mu-7VUKZOT8Qe2gdSaOj5aCWOLvCVc',
    appId: '1:1037548014539:ios:b30862135dd201c5eac44e',
    messagingSenderId: '1037548014539',
    projectId: 'estoquepro-dev',
    databaseURL: 'https://estoquepro-dev-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-dev.firebasestorage.app',
    iosBundleId: 'br.com.qi0development.estoquePro.dev',
  );
}
