// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPl_38c_cbFVqiR3L27Pr3R_WqdC7gj9E',
    appId: '1:1050884143688:web:bd0efb323e8c6a7556367d',
    messagingSenderId: '1050884143688',
    projectId: 'estoquepro-35ecd',
    authDomain: 'estoquepro-35ecd.firebaseapp.com',
    databaseURL: 'https://estoquepro-35ecd-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-35ecd.firebasestorage.app',
    measurementId: 'G-K0KTVLY91W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1g8FsizZDyITxryEyoTeOjUf760MFLk',
    appId: '1:1050884143688:android:e10e7d71d10d298756367d',
    messagingSenderId: '1050884143688',
    projectId: 'estoquepro-35ecd',
    databaseURL: 'https://estoquepro-35ecd-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-35ecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MVhwjBBJcs3JSurr8dXmWxeJ98Rk-tc',
    appId: '1:1050884143688:ios:ffe689bf16108af756367d',
    messagingSenderId: '1050884143688',
    projectId: 'estoquepro-35ecd',
    databaseURL: 'https://estoquepro-35ecd-default-rtdb.firebaseio.com',
    storageBucket: 'estoquepro-35ecd.firebasestorage.app',
    iosBundleId: 'br.com.qi0development.estoquePro',
  );
}
