include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve
  page_width: 120

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
